<template>
  <LayoutHero>
    <div class="flex bg-white shadow-lg rounded-lg">
      <div class="flex-1 p-10">
        <h1 id="About">A Generative Journey </h1> <!--Add padding-->
            <p>When you look around society at large you'll find that most people are specialists who do one thing well. In fact, society incentivises and rewards such behaviour, which in turn shapes the behaviour of people in its image. <strong> I'm not one of those people. </strong> </p> 
            <p> For whatever reason, I've never been satisfied doing "just one thing" and have a drive to transcend disciplines while including new skills. Such people are often called "polymaths", "generalists", "multipotentiates", "pantologists" or more simply "renaissance people". We're a minority in what seems like a sea of madness but historically the most curious cats out there seem to fall into these categories; Plato, Pythagoras, DaVinci, <a href="https://www.youtube.com/watch?v=hrcJz63En94&list=PLANorT3Y7McMKzxqTw8u8ykq3pe_6A0Tn"> Maynard James Keenen</a>, <a href="https://www.youtube.com/watch?v=KdnGPQaICjk">Ted Nelson</a>, <a href="https://www.dgmlive.com/in-depth/the-guitar-circle-book-table-of-contents">Robert Fripp (King Crimson)</a>, Steve Jobs and Sylvain Richard (20syl). </p>
            
            <p> <h3>This is my personal story, scroll to the bottom for a list of links! </h3> </p>
            
            <p>The first skill I remember getting reasonably good at was the guitar, however its also the speciality I'm probably least proficient in as I learnt without any particular framework or discipline! It was a practice that led to related endeavours like building a replica Gibson Les Paul and dabbling with home recording... Guitar building was a one time passion project but home recording eventually led to a <strong> Masters degree in Audio Technology</strong>.</p>
            <p> <strong>Heres a picture of said guitar and a video of me performing some material I wrote: </strong></p>
            <div class="flex justify-center grid-cols-2 gap-12 bg-primary-200 rounded-lg p-4 mb-4"> <!-- Justify centre is the closes to what I want but not evenly spaced -->
              <div> <g-image src="~/assets/img/lesPaul.jpg" width="315" height="315" fit="contain">LesPaul</g-image> </div>
              <div> <iframe width="560" height="315" src="https://www.youtube.com/embed/HYDHSt-9z0c" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> </div>
            </div>
            <p>As mentioned, playing the guitar opened up many doors; like many teenagers I was into rock music and I started out on an electric guitar but as my tastes matured I started to enjoy playing an acoustic. Not wishing to limit myself I started to pick up a cornicopia of other instruments; drums, bass, mandolin, harmonica, didgeredoo and just about anything else physically available to me. </p>
            <p>En route to a masters in Audio I took a detour through the circus arts, dance and object manipulation... which along with board sports helped hone my physical dexterity and coordination. Juggling's in itself is super interesting and has its own symbol language called <a href="http://www.twjc.co.uk/jugglingnotations.html">siteswap</a> to describe types of throws! (as exhibited in some of the verrry old shots below - circa age 18)</p>
            
            <div class="flex justify-center grid-cols-2 gap-12 bg-primary-200 rounded-lg p-4 mb-4">
              <div> <iframe width="560" height="315" src="https://www.youtube.com/embed/dpC7pGyaLLg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> </div>
            </div>
            <p>This brings us up to the point of leaving school... At this point, the garden of forking paths could have gone many directions but upon finishing I decided to take a year out, earn some cash to buy recording equipment to set myself up for more serious study over the next few years. This was a top of the range Mackbook Pro and a Digidesign 002 desk that I got second hand from my friends dad who was professional musician. </p>
            <p>Somewhere over this stint, myself and a peer volunteered to do some live sound at a music festival and ended up running a small tent with no scheduled acts... so we took on stage management duties and ended up recruiting anyone we saw moving between stages with instruments! While scouring the waterlogged planes of the ironically names "Solace" festival we stumbled upon a local Cork band called Neon Flea Circus and invited them to play, they obliged with a blistering gig and we offered to record them. This project took on a life of its own across a variety of locations and with whatever equipment we could cobble together we recorded a creative commons album that <strong>absolutely bloody rocked!!</strong></p>
            <p>Given we were releasing the art for free, I got very interested in the commerce aspect of music marketing and decided to do the album promotion for a final year project (along with recordings from another band we also met at Solace named "Sons of Gingerbread"). Surprisingly we did manage to turn a buck from releasing a free album in conjunction with a national tour and merchandise. For these efforts I graduated with a 1:1, and earned myself a scholarship to do a masters degree at the same university which took two years part-time. </p>

            <div class="flex rounded-lg"> <!-- Works locally but not on Netlify-->
              <iframe class="flex rounded-lg mb-6" width="1150" height="678" src="http://neonfleacircus.com/download/index.php"></iframe> <!--why flex no work-->
            </div>

            <p>During this period I spent time investigating how we subjectivly interpret sound and the driving question of "what is music?". This initiative started by prototyping 'musical' distortion units in a program called MaxMSP, which I used to track and manipulate fundemental frequencies. Surround sound recording techniques also caught my attention; I wanted to know "how do we capture the sound of physical enviroments and reproduce such richness in our living rooms?". To find out, I experimented with a number of techniques leveraging <i> head related transfer functions</i>: <a href="https://en.wikipedia.org/wiki/Binaural_recording">binaural heads</a>, <a href="https://lossenderosstudio.com/article.php?subject=17">hamasaki squares and optimised cardioid triangles</a> to be precise. All just different models for mapping the terrain in various ways. </p> 
            <p>Eventually my research cumulated in the question of "why do we tend to prefer the aesthetic qualities of certain sounds over others?" and namely I focused on the age old debate of analogue vs digital (specifically tubes vs transistors) which eventually surfaced the inherent laws of vibration; precicely what pythogoras meant when he proclaimed "the octave never repeats". In this case it turned out that tubes produce second (rather than third) order harmonic distortion, leading to intermodulation frequencies (sum and difference) and giving rise to the <a href="https://en.wikipedia.org/wiki/Pythagorean_tuning">pythagorean mucical scale</a> at smaller and smaller fractal dimensions! </p>
            
            <div class="flex justify-center grid-cols-2 bg-primary-200 rounded-lg p-4 mb-4">
              <iframe src="https://player.vimeo.com/video/19152308" width="560" height="315" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
              <iframe src="https://player.vimeo.com/video/108854060" width="560" height="315" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
            </div>

            <p>Having polished other peoples music for several years, I decided to get self indulgent for my masters project by writing and recording a concept album in 5.1 surround sound. The production turned out pretty well (lyrics, songwriting, musicianship and recording), though to be perfectly honest it wasn't as life affirming as the Fleas stuff I'd previously poured my heart and soul into - it had slightly less character from the more sterile "professional" spaces which I feel reduced its dimensionality, even if the sonic depth was of higher fidelity. Still it scratched an itch for self expression and I got to wear many hats!</p>
            <div>
              <iframe class="mb-4" width="100%" height="350" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1147256257%3Fsecret_token%3Ds-wDjI70jMrZY&color=%237c6854&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
            </div>

            <p>Post education I enetered into the arena of live sound, at first part time in <a href="https://barnightjar.com/">Bar Nightjar</a> which was a small but fun jazz bar, and then filled out my time with other freelance gigs such as quality control for DVD & BluRay at <a href="https://www.thisismetropolis.com/">Metropolis Chiswick</a>. After this things broadened into running lights, sound and media centers for a hotel chain in Portugal which was unfulfilling but paid the bills. </p> 
            <p>Upon return to the UK I leveraged this experience and got a position as Technical Manager for Shoreditch Bar Group, a dysfunctional organisation responsible for the serfdom of Shoreditch but a playground of broken systems scattered around a local radius. I learnt quite a lot in this enviroment of scarcity like programming ShowCAD or how to fix lights, while picking up various electric and electronic repair tricks (as well as a few shocks and scars). </p> 
            <p>At some stage though I'd had enough of Shoreditch serfdom and decided to form my own company with some other technical managers I got to know from around other venues. Things started to look up as I got contracted by my old employer at Bar Nighjar to build their sister venues <a href="https://www.oriolebar.com/">Oriole's</a> stage and sound system, which would be used for live jazz seven days a week. The next bits of luck were other venue comissions for a high end bar/resturant in Monument called <a href="https://www.mber.london/">Mber</a> and another called in Soho called <a href="https://www.barswift.com/">Swift</a>.</p>
            
            <!-- insert pictures here
            <ldiv class="flex justify-center grid-cols-2 bg-primary-200 rounded-lg p-4 mb-4">
              <div> <g-image src="" width="315" height="315" fit="contain">Oriole</g-image> </div>
              <div> <g-image src="" width="315" height="315" fit="contain">Mber</g-image> </div>
              <div> <g-image src="" width="315" height="315" fit="contain">Swift</g-image> </div>
            </div>
            -->

            <p> Around this time I also started to pick up more club gigs and got contracted as the Tech Manager for EggLDN which is a pretty well known techno club. I was typically managing freelancers or operating lights for various well known acts (one of the most notorious <a href="https://www.youtube.com/watch?v=8JAMkrzSRao">dickheads in dance music</a> was a fan!). Like most of the jobs mentioned, I pretty much learned to program the Avolights desks by playing with them.</p>
            
            <div class="flex justify-center grid-cols-2 bg-primary-200 rounded-lg p-4 mb-4">
              <iframe width="560" height="315" src="https://www.youtube.com/embed/8JAMkrzSRao" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        
            <p>Alas, graveyard shifts were slowly killing me and so I felt an impetus to get out of the entertainment industry and I didnt really know what to do. In my relativly ample spare time I was digging through what I came to recognise as systemic legal corruption and while following the money I started learning about the global financial system. Concerned about the money printing I decided to "buy out" of fiat currency into silver and gold. </p> 
            <p>Pretty quickly this investigation led me into the waters of digital currency and I found bitcoin (again), which I had a modicum of success in. This took me right into the heart of the crypto currency scene just as the infamous DAO hack was unfolding. At this point I started experimenting with "alt-coins" and started buying ETH at $7 about a year before the scene was frothing in ICO madness. I ingested every second of this so called "cambrian explosion" learning the ins and outs of mechanism design and a still nascent computing paradigm. One of the ICOs I was watching at the time was Pillar Project, who we're inviting people out to Slovakia to an unconference they were hosting so I went along and a month or two later I ended up hired to work with them on "the personal data locker". <strong>This turned out to become of the toughest learning experiences of my life, but one of the most worthwhile!</strong></p>
            <p>Its still hard for to articulate exactly what happened at that company over the following year or so, but I've got at least a basic understanding of the patterns now. At the high level it was <a href="https://en.wikipedia.org/wiki/Spiral_Dynamics">"spiral dynamics"</a> or emergence in action, while everyone present tried to hold on for dear life! At no point did the place feel remotely "safe" and navigating the complexity required artful participation - something I lacked. I wasnt creative enough to pass safely between the rocks and the whirlpool unscathed but the experience was a master class in dealism. It was ugly and terrifying, but humans were left to be humans while learning to achieve results - something I still wholeheartedly endorse. One thing now obvious from that experience, is that we sapeins are particularly uncomfortable with uncertaintity and embracing 'the void'. Like a jazz band - if we cant play on our own - then we're utterly screwed as a collective...</p>
            <p>I've been through this a few times now and its always pretty mad; we start trying to build structues and hierarchys and without a clue what were doing. People try to subordinate others to their will, at any cost and will play whatever kind of games they're able to get away with to achieve their ends. Might is right, at least in the early stages. At Pillar, the MBAs controling the funds appointed themselves fancy titles and positions of power to fill the void. I thought this was all nonsense and foul play while kicking up an almighty fuss, behaviour I regret, but once others accepted the behaviour it was legitimised and became a real thing. Coincidentally this is how currency and legal entities function... we fall for myths and fail to question fiction. Don't listen to the popular opinion or new age mythic literals; <strong> don't believe</strong>, but pretend you do or perish! </p>
            <p>I worked on practically everything there; mechanism design, distributed key management, product design, project management (incognito), archetecture, code, ecommerce, exchanges, intelligance, strategy, communication and (ugh) marketing. In short I made use of the enviroment and learnt as much as possible about what to do and what not to do... foot in mouth and head up arse! </p>
            <p>Heres where it gets interesting, as while immersed in chaos I thought it would be a good idea to take some plant medicine with a Shaman. Actually, I drank auyhuesca twice over this period with a rascal known as Rangy Tangy; once in the early days of the project while trying to get an exchange off the ground and another while in the midst of a six hundred person self-rganising unconference. Both were incredible experiences of utter nothingness but I didn't get sucked into the kelidoscope to be swoddled in the loving arms of universe; more an intimate experience of nothingness, followed by collision into the brick wall of somethingness. Maybe I should have succumbed to the plant? the ceremonies I was involved in were sitting ceremonies, so I sat through them upright - rather than on my back!</p>
            <p>After pushing the rock uphill for a year and a half, with vultures pecking my back, I was made redundant in the great ETH crash of 2018. It made sense to me, I wasn't complying with the MBA's arbitrarily imposed structures so I'd marked myself. They had a very close collegue do their dirtywork in the mass layoff; 'your in charge of these animals Jack, pick two to help you and put the rest down'... so I offered to go. The decision was already made though - the dominant autocrat wanted to make the experience a stab at my ego (perhaps more a reflection of his) so he made sure not to accept the offer and said to wait - I felt for my college who thanked me for making it easy. Relieved of my percieved duty, I was overjoyed and more than happy to go. While others went to the pub to mourn their losses, I got in touch with good friends and made myself available again. We lit a few joints and flew drones! </p>
            <p>Going forward I moved on to the place advertising more wholistic patterns like Holocracy and put the skills I'd developed into practice at Giveth a crypto charity. It wasn't what I'd envisioned, but I figured it was a good start and started memetically hacking "The Commons Stack" - which emerged from seeding language around Elinor Ostroms famous work "Governing the Commons". This was pretty successful and five motley crews came together to "meta-hack" the project together during the Odyssey 2019 hackathon (while coliving/coworking on a pirate ship called "Mars"). This went well, I was a "Jedi" doing networking and communication and several of our teams got prizes which covered the boat. The stories told and the collective dream(s) were beautiful; leverage cryptographic primitives to build and barter social critical infrastructure while manifesting moving cities by living the experience... on pirate ships of course! We were incubating a prosocial idea of "Hack-alongs, not Hackathons"</p>
            <p>Around this time my mental models were starting to fall into place; I'd always read the kinds of books you'd find on an Ivy Leagues reading list like Kannaman, Taleb and other intellectual heavyweights - but at this point I was on to the likes of Gurdjieff and Robert Anton Wilson, the weird and wonderful! Everything I'd learnt up until this point had started to come together and integrate into a second order meta-model; I saw causal patterns everywhere and soon after I was recommended the Riso-Hudson enneagram model which unlocked the social matrix... "The work" was also clearly legit given the description of DNA - five years before its discovery, as well as "the laws of vibration" which I'd figured out for myself during my masters study in Audio Engineering. 
            
            <p>Unfortunatly though the Commons Stack dream was not to be; I had to let go and move on as those amongst us with more colonial tendancies captured the project by claiming the abstract group identity and then controlling the narrative (#censored). Given this fragmentation and my lack of income I decided it would be more productive to jump ship and work with the bright people I'd formed an appreciation for - luckily a far more promising <a href="http://liminalvillage.com">endevour!</a> </p> 
            <p>Around July 2019 we started running our first <a href="http://hackalong.io">Hackalong</a>, an inital incarnation of shared dreams brewed up at Odyssey; requisite variety to propogate and harden the group infoset using the Lunar cycles as a timeline! By using open space technology we designed for chaos, so it was messy, but it also kind of worked. We failed quickly at a lot of practices by testing our assumptions about the digital space in physical reality - Holocracy/Sociocracy, Offers/Requests, Claims/Attestations, Design Thinking and various other experiments. Despite some tensions due to collisiding ideologies a number of us formed lasting connections which would later resurface in differnt incarnations. </p>
            <p>As the first <a href="http://Hackalong.io">Hackalong</a> closed, I left for a friends wedding in Poland after which I took a bus to Vienna and got a few weeks rest in a cheap hostel, while wandering around and getting a feel for exquisite the cultural and historical context. The next port of call was the "hackalong houseshare" during Berlin Blockcahin week. I volenteered at the Web3Summit, EthBerlin and Token Engineering Summit while also attending the Outlier Ventures Diffusion event, EthBerlinZwei hackathon and OpenSource Salon. Our pioneer ecosystem was propogating, making connections and gaining visibility! </p>
            <p>I stuck around Berlin a short while to bask in the sunny parks before heading off to Prague on a whim to try and volenteer at Rebooting the Web of Trust confrence - which I was denied. So like a true pirate, I hung around in the Institute of Crypto Anarchy drinking coffee and writing, while participating in the conferences breakout groups that came downstairs! When RWOT was over myself and some friends built an "offers" module on Holochain during the hackathon they had organised. </p> 
            <p>After Prague, I took a bus over to a friends in Zutphen (Holland) where I'd spend a few weeks recovering from the intense travel, while also checking-in on his movements at SocialTec. Kindly Michiel provided an ideal setting in the woods to wind down in with a cozy guest apartment and was happy for the lovely Maija to stay as well. We spent time wandering the woods while she enlightened me on the various forms of local plantlife. </p> 
            
            <p>At this point there was a gap in my itenary so I went back to Liminal Village once again for Hackalong 0.2 - a smaller event with a few active members. Kay had decided that Sococo (a paid digital work enviroment) was a total rip off for its minimal feature set and needed open-sourcing, so he and Sam hacked together the first iteration of a platform called interspace.chat - which essentially enabled jit.si with some break out room functionality and a lo-fi bitmap interface. </p>
            <p>The Diffusion schelling point was on my radar, so I booked a return flight to Berlin and back where I met some friends and worked on a set of smart contracts that were essentially a prototype for an Ethereum based reputation system. The last night was pretty magical; there was a festival of lights and the dontation based bar next to my hostel was projecting mapping an adjecent church. Having peacefully sat drinking with the equipment supervisors, their curiosity for the mapping software (Resolume) started to pique - this was the same technology I'd previously worked with in the clubs, so having built trust already I was permitted to show them how to play with it! </p>
            <p>After a short stop over in Liminal, I flew to Ireland and spent Christmas with family and friends which adjourned my travels for 2019. This hiatus ony lasted for about a month and a half before 2020 took me on towards another Holochain hackathon in early January, this time in Lisbon. I arrived a few days early to do a bit of work, investigate the city sights and catch up with a few community friends. Unfortunatly, there was a bit of a drama regarding a mix up of timing and communication breakdown that followed me much further than I would have liked; essentially a mixed up rendevous date triggered the experiences manager and put our relationship into a nose dive. Despite this minor discomfort, I managed to start some work with a peer on a social graph project that continued to percolate for quite some time. </p>
            <p>Thomas had also been enlisted to help a lady that was working on an ecocommunity and requested my involvement, so after a few days more in Lisbon I hopped a bus to Majorca and go and meet her. Unfortunatly, she was relativly incongruent with her espoused beliefs and the living enviroment was a bit sterile for my liking, as a result I decided to move on to the city where I found an atmosphere that was much more alive and vibrant. Over this period my grandfather also passed away which was probably hard for my father but having made it to one hundred years old with dementia and various disabilities the family was mostly prepared. I took a flight back to London for a short period staying with a good friend before embarking on a trip to Norwich where he was to be burried. </p>
            <p> Odyssey Polaris </p>
            <p>I returned to Liminal just as the COVID-19 pandemic was engulfing the world. Upon landing I was greeted by an apocalyptical immigration officer in a Hazmat suit, who foisted a tempreture gun upon me, pointing it directly at my forehead... about then that I realized the Corona crazyness was getting pretty serious! I'd landed in a good place for a lockdown though as Liminal Village was in transformation for just the occasion. The Italian countryside had ample room and there was plenty of rennovation work to get done; roads, water systems, gardens and terraces all needed to get built as well some soil regeneration work! </p>
            <p>Having previously applied on a whim, I'd been granted a scholarship for "Capra Course - The Systems View of Life" and so spent twelve weeks diving into the <a href="https://roamresearch.com/#/app/Liminal_Village/page/lNXlzFk8N">primitives</a> which underpin complexity theory, first order cybernetics, biology and self organisation - amongst other topics! Over this period I also spent a good deal of energy learning about Holochain by participating on both the archetecture and business courses they were running, as well as their community "hackalongs" which were an emergent community initiative integrating some of our memes.</p>
            <p>In August, the guest house that I was staying in was rented out for the peak season so I returned back to Ireland, passing the two week quarrentene preiod by learning some Vue.js (building this site) and participating in the Holochin Devcamp where I became more confident with the framework through practice (thanks Nastasia!). After about a month and a half in the emerald Isles I flew back to Liminal for another Hackalong where a number of people were congregating. </p>
            <p>This gathering was pretty full blown with many guests and a good degree of continuity. Things started slowly but pretty quickly ramped up and flows of energy and resources corssed in and out of the local membrane; at first it was just myself, Thomas, Roberto, Laura and (new attendee) Nienke but gradually scaled to include Federico, Jason, Ome, Hersch, Valentina, Ollie and Tim. Odyssey Momentum was pretty close so we were gearing up to participate in that which included a pretty intense sprint while navigating group tensions. One participant was particularly explosive and was excersising their personal deamons, which disrupted a lot of potential but after a while I opted out of consensus reality and just got on with work in preparation for the hack. This paid off to large degrees as my team working on distributed identity management won the track to take home €4k, we're also now starting to inform the dutch blockchain coalitions SSI framework.

            <p>Bringing us up to today!</p>

            
            <!--
            - [[Portfolio]]
                    - [Boris Brejcha @ Egg London 2017 Pt. 1](https://www.youtube.com/watch?v=k0wpI_IxWzA)
                    - [Erick Morillo @Egg LDN 2016](https://www.youtube.com/watch?v=8JAMkrzSRao)
                    - [Egg London going off](https://www.youtube.com/watch?v=R5l3Bc19_A4)
                    - [Boris Brejcha @ Egg London (01.07.2017)](https://www.youtube.com/watch?v=Yems6-_PWHk)
                    - [WILL ATKINSON LIVE @ KEARNAGE - TRANCE SANCTUARY - EGG LONDON (18-11-2017)](https://www.youtube.com/watch?v=B03-YqPajYg)
                    - [Claptone - The Drums (Din Daa Daa) feat. George Kranz @ Egg London](https://www.youtube.com/watch?v=D-2O6_m8_L8)
                    - [Noise & Girls at EGG LDN - Chris Thomas](https://www.youtube.com/watch?v=rg8KmUZJVvA)
                    - [Dense & Pika @ Familia, EGG, London 14/01/2017 [Part 1/2]](https://www.youtube.com/watch?v=nUP709jlEq8)
                    - [ISHU DEFT @ Egg London (Terrace)25/03/2017](https://www.youtube.com/watch?v=T9OCm2ZD6lk)
                    - [Miky J - Egg London 28 - 01 - 2017 Part 1](https://www.youtube.com/watch?v=-nS0pmaWTc8)
                -->
      </div>
    </div>
  </LayoutHero>
</template>

<script>
export default {
  metaInfo: {
    title: "Skills"
  },

  data() {
    return {
      cards: [
        {
          title: "this one has a link",
          img: "https://picsum.photos/600/300",
          link: "https://vuejs.org/v2/guide/components-props.html",
          content:
            "blanditiis animi sequi beatae nisi facilis maiores voluptate doloribus necessitatibus est laborum vel. Quasi, nisi. "
        },
        {
          title: "hello world",
          img: "card.png",
          extraClassImg: "h-64",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis neque, mollitia a magni ducimus aliquam blanditiis animi sequi beatae nisi facilis maiores voluptate doloribus necessitatibus est laborum vel. Quasi, nisi. "
        },

        {
          title: "No image here",
          content:
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis neque, mollitia a magni ducimus aliquam blanditiis animi sequi beatae nisi facilis maiores voluptate doloribus necessitatibus est laborum vel. Quasi, nisi. "
        }
      ]
    };
  }
};
</script>

<style lang="scss">
</style>
